[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd iop-sdk-python-1.0.2 && . /opt/venv/bin/activate && pip install -e ."
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python -c 'import app'"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:app"
